server:
  port: ${SERVER_PORT:9080}

spring:
  application:
    name: flashmall-gateway
  config:
    import:
      - "optional:nacos:flashmall-common.yaml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
      - "optional:nacos:${spring.application.name}.yaml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        file-extension: yaml
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
    sentinel:
      eager: true
      transport:
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8858}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 用户服务
        - id: flashmall-user
          uri: lb://flashmall-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        # 商品服务
        - id: flashmall-goods
          uri: lb://flashmall-goods
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix=1

        # 订单服务
        - id: flashmall-order
          uri: lb://flashmall-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1

        # 库存服务
        - id: flashmall-stock
          uri: lb://flashmall-stock
          predicates:
            - Path=/api/stock/**
          filters:
            - StripPrefix=1

logging:
  level:
    com.flashmall.gateway: debug

flashmall:
  traffic:
    gateway:
      user-qps: ${GATEWAY_USER_QPS:30}
      goods-qps: ${GATEWAY_GOODS_QPS:30}
      order-qps: ${GATEWAY_ORDER_QPS:20}
      stock-qps: ${GATEWAY_STOCK_QPS:20}
